My Project: SPI access
SPI access
Functions
int bcm2835_spi_begin (void)
void bcm2835_spi_end (void)
void bcm2835_spi_setBitOrder (uint8_t order)
void bcm2835_spi_setClockDivider (uint16_t divider)
void bcm2835_spi_setDataMode (uint8_t mode)
void bcm2835_spi_chipSelect (uint8_t cs)
void bcm2835_spi_setChipSelectPolarity (uint8_t cs, uint8_t active)
uint8_t bcm2835_spi_transfer (uint8_t value)
void bcm2835_spi_transfernb (char *tbuf, char *rbuf, uint32_t len)
void bcm2835_spi_transfern (char *buf, uint32_t len)
void bcm2835_spi_writenb (char *buf, uint32_t len)
Detailed Description
These functions let you use SPI0 (Serial Peripheral Interface) to interface with an external SPI device.
Function Documentation
int bcm2835_spi_begin (void)
Start SPI operations. Forces RPi SPI0 pins P1-19 (MOSI), P1-21 (MISO), P1-23 (CLK), P1-24 (CE0) and P1-26 (CE1) to alternate function ALT0, which enables those pins for SPI interface. You should call bcm2835_spi_end() when all SPI funcitons are complete to return the pins to their default functions.
See Also
bcm2835_spi_end()
Returns
1 if successful, 0 otherwise (perhaps because you are not running as root)
References bcm2835_gpio_fsel(), BCM2835_GPIO_FSEL_ALT0, bcm2835_peri_write(), bcm2835_peri_write_nb(), bcm2835_spi0, BCM2835_SPI0_CS, BCM2835_SPI0_CS_CLEAR, RPI_GPIO_P1_19, RPI_GPIO_P1_21, RPI_GPIO_P1_23, RPI_GPIO_P1_24, and RPI_GPIO_P1_26.
 {
     volatile uint32_t* paddr;
     /* Set the SPI0 pins to the Alt 0 function to enable SPI0 access on them */
     bcm2835_gpio_fsel(RPI_GPIO_P1_26, BCM2835_GPIO_FSEL_ALT0); /* CE1 */
     bcm2835_gpio_fsel(RPI_GPIO_P1_24, BCM2835_GPIO_FSEL_ALT0); /* CE0 */
     bcm2835_gpio_fsel(RPI_GPIO_P1_21, BCM2835_GPIO_FSEL_ALT0); /* MISO */
     bcm2835_gpio_fsel(RPI_GPIO_P1_19, BCM2835_GPIO_FSEL_ALT0); /* MOSI */
     bcm2835_gpio_fsel(RPI_GPIO_P1_23, BCM2835_GPIO_FSEL_ALT0); /* CLK */
     /* Set the SPI CS register to the some sensible defaults */
     paddr = bcm2835_spi0 + BCM2835_SPI0_CS/4;
     bcm2835_peri_write(paddr, 0); /* All 0s */
     /* Clear TX and RX fifos */
     bcm2835_peri_write_nb(paddr, BCM2835_SPI0_CS_CLEAR);
     return 1; // OK
 }
void bcm2835_spi_chipSelect (uint8_t cs)
Sets the chip select pin(s) When an bcm2835_spi_transfer() is made, the selected pin(s) will be asserted during the transfer.
Parameters
[in] cs Specifies the CS pins(s) that are used to activate the desired slave. One of BCM2835_SPI_CS*, see bcm2835SPIChipSelect
References bcm2835_peri_set_bits(), bcm2835_spi0, BCM2835_SPI0_CS, and BCM2835_SPI0_CS_CS.
 {
     volatile uint32_t* paddr = bcm2835_spi0 + BCM2835_SPI0_CS/4;
     /* Mask in the CS bits of CS */
     bcm2835_peri_set_bits(paddr, cs, BCM2835_SPI0_CS_CS);
 }
void bcm2835_spi_end (void)
End SPI operations. SPI0 pins P1-19 (MOSI), P1-21 (MISO), P1-23 (CLK), P1-24 (CE0) and P1-26 (CE1) are returned to their default INPUT behaviour.
References bcm2835_gpio_fsel(), BCM2835_GPIO_FSEL_INPT, RPI_GPIO_P1_19, RPI_GPIO_P1_21, RPI_GPIO_P1_23, RPI_GPIO_P1_24, and RPI_GPIO_P1_26.
 {
     /* Set all the SPI0 pins back to input */
     bcm2835_gpio_fsel(RPI_GPIO_P1_26, BCM2835_GPIO_FSEL_INPT); /* CE1 */
     bcm2835_gpio_fsel(RPI_GPIO_P1_24, BCM2835_GPIO_FSEL_INPT); /* CE0 */
     bcm2835_gpio_fsel(RPI_GPIO_P1_21, BCM2835_GPIO_FSEL_INPT); /* MISO */
     bcm2835_gpio_fsel(RPI_GPIO_P1_19, BCM2835_GPIO_FSEL_INPT); /* MOSI */
     bcm2835_gpio_fsel(RPI_GPIO_P1_23, BCM2835_GPIO_FSEL_INPT); /* CLK */
 }
void bcm2835_spi_setBitOrder (uint8_t order)
Sets the SPI bit order NOTE: has no effect. Not supported by SPI0. Defaults to
Parameters
[in] order The desired bit order, one of BCM2835_SPI_BIT_ORDER_*, see bcm2835SPIBitOrder
void bcm2835_spi_setChipSelectPolarity (uint8_t cs, uint8_t active)
Sets the chip select pin polarity for a given pin When an bcm2835_spi_transfer() occurs, the currently selected chip select pin(s) will be asserted to the value given by active. When transfers are not happening, the chip select pin(s) return to the complement (inactive) value.
Parameters
[in] cs The chip select pin to affect
[in] active Whether the chip select pin is to be active HIGH
References bcm2835_peri_set_bits(), bcm2835_spi0, and BCM2835_SPI0_CS.
 {
     volatile uint32_t* paddr = bcm2835_spi0 + BCM2835_SPI0_CS/4;
     uint8_t shift = 21 + cs;
     /* Mask in the appropriate CSPOLn bit */
     bcm2835_peri_set_bits(paddr, active << shift, 1 << shift);
 }
void bcm2835_spi_setClockDivider (uint16_t divider)
Sets the SPI clock divider and therefore the SPI clock speed.
Parameters
[in] divider The desired SPI clock divider, one of BCM2835_SPI_CLOCK_DIVIDER_*, see bcm2835SPIClockDivider
References bcm2835_peri_write(), bcm2835_spi0, and BCM2835_SPI0_CLK.
 {
     volatile uint32_t* paddr = bcm2835_spi0 + BCM2835_SPI0_CLK/4;
     bcm2835_peri_write(paddr, divider);
 }
void bcm2835_spi_setDataMode (uint8_t mode)
Sets the SPI data mode Sets the clock polariy and phase
Parameters
[in] mode The desired data mode, one of BCM2835_SPI_MODE*, see bcm2835SPIMode
References bcm2835_peri_set_bits(), bcm2835_spi0, BCM2835_SPI0_CS, BCM2835_SPI0_CS_CPHA, and BCM2835_SPI0_CS_CPOL.
 {
     volatile uint32_t* paddr = bcm2835_spi0 + BCM2835_SPI0_CS/4;
     /* Mask in the CPO and CPHA bits of CS */
     bcm2835_peri_set_bits(paddr, mode << 2, BCM2835_SPI0_CS_CPOL | BCM2835_SPI0_CS_CPHA);
 }
uint8_t bcm2835_spi_transfer (uint8_t value)
Transfers one byte to and from the currently selected SPI slave. Asserts the currently selected CS pins (as previously set by bcm2835_spi_chipSelect) during the transfer. Clocks the 8 bit value out on MOSI, and simultaneously clocks in data from MISO. Returns the read data byte from the slave. Uses polled transfer as per section 10.6.1 of the BCM 2835 ARM Peripherls manual
Parameters
[in] value The 8 bit data byte to write to MOSI
Returns
The 8 bit byte simultaneously read from MISO
See Also
bcm2835_spi_transfern()
References bcm2835_peri_read(), bcm2835_peri_read_nb(), bcm2835_peri_set_bits(), bcm2835_peri_write_nb(), bcm2835_spi0, BCM2835_SPI0_CS, BCM2835_SPI0_CS_CLEAR, BCM2835_SPI0_CS_DONE, BCM2835_SPI0_CS_TA, BCM2835_SPI0_CS_TXD, and BCM2835_SPI0_FIFO.
 {
     volatile uint32_t* paddr = bcm2835_spi0 + BCM2835_SPI0_CS/4;
     volatile uint32_t* fifo = bcm2835_spi0 + BCM2835_SPI0_FIFO/4;
     uint32_t ret;
     /* This is Polled transfer as per section 10.6.1
     // BUG ALERT: what happens if we get interupted in this section, and someone else
     // accesses a different peripheral?
     // Clear TX and RX fifos
     */
     bcm2835_peri_set_bits(paddr, BCM2835_SPI0_CS_CLEAR, BCM2835_SPI0_CS_CLEAR);
     /* Set TA = 1 */
     bcm2835_peri_set_bits(paddr, BCM2835_SPI0_CS_TA, BCM2835_SPI0_CS_TA);
     /* Maybe wait for TXD */
     while (!(bcm2835_peri_read(paddr) & BCM2835_SPI0_CS_TXD))
     ;
     /* Write to FIFO, no barrier */
     bcm2835_peri_write_nb(fifo, value);
     /* Wait for DONE to be set */
     while (!(bcm2835_peri_read_nb(paddr) & BCM2835_SPI0_CS_DONE))
     ;
     /* Read any byte that was sent back by the slave while we sere sending to it */
     ret = bcm2835_peri_read_nb(fifo);
     /* Set TA = 0, and also set the barrier */
     bcm2835_peri_set_bits(paddr, 0, BCM2835_SPI0_CS_TA);
     return ret;
 }
void bcm2835_spi_transfern (char * buf, uint32_t len)
Transfers any number of bytes to and from the currently selected SPI slave using bcm2835_spi_transfernb. The returned data from the slave replaces the transmitted data in the buffer.
Parameters
[in,out] buf Buffer of bytes to send. Received bytes will replace the contents
[in] len Number of bytes int eh buffer, and the number of bytes to send/received
See Also
bcm2835_spi_transfer()
References bcm2835_spi_transfernb().
 {
     bcm2835_spi_transfernb(buf, buf, len);
 }
void bcm2835_spi_transfernb (char * tbuf, char * rbuf, uint32_t len)
Transfers any number of bytes to and from the currently selected SPI slave. Asserts the currently selected CS pins (as previously set by bcm2835_spi_chipSelect) during the transfer. Clocks the len 8 bit bytes out on MOSI, and simultaneously clocks in data from MISO. The data read read from the slave is placed into rbuf. rbuf must be at least len bytes long Uses polled transfer as per section 10.6.1 of the BCM 2835 ARM Peripherls manual
Parameters
[in] tbuf Buffer of bytes to send.
[out] rbuf Received bytes will by put in this buffer
[in] len Number of bytes in the tbuf buffer, and the number of bytes to send/received
See Also
bcm2835_spi_transfer()
References bcm2835_peri_read(), bcm2835_peri_read_nb(), bcm2835_peri_set_bits(), bcm2835_peri_write_nb(), bcm2835_spi0, BCM2835_SPI0_CS, BCM2835_SPI0_CS_CLEAR, BCM2835_SPI0_CS_DONE, BCM2835_SPI0_CS_RXD, BCM2835_SPI0_CS_TA, BCM2835_SPI0_CS_TXD, and BCM2835_SPI0_FIFO.
Referenced by bcm2835_spi_transfern().
 {
     volatile uint32_t* paddr = bcm2835_spi0 + BCM2835_SPI0_CS/4;
     volatile uint32_t* fifo = bcm2835_spi0 + BCM2835_SPI0_FIFO/4;
     uint32_t TXCnt=0;
     uint32_t RXCnt=0;
     /* This is Polled transfer as per section 10.6.1
     // BUG ALERT: what happens if we get interupted in this section, and someone else
     // accesses a different peripheral?
     */
     /* Clear TX and RX fifos */
     bcm2835_peri_set_bits(paddr, BCM2835_SPI0_CS_CLEAR, BCM2835_SPI0_CS_CLEAR);
     /* Set TA = 1 */
     bcm2835_peri_set_bits(paddr, BCM2835_SPI0_CS_TA, BCM2835_SPI0_CS_TA);
     /* Use the FIFO's to reduce the interbyte times */
     while((TXCnt < len)||(RXCnt < len))
     {
         /* TX fifo not full, so add some more bytes */
         while(((bcm2835_peri_read(paddr) & BCM2835_SPI0_CS_TXD))&&(TXCnt < len ))
         {
            bcm2835_peri_write_nb(fifo, tbuf[TXCnt]);
            TXCnt++;
         }
         /* Rx fifo not empty, so get the next received bytes */
         while(((bcm2835_peri_read(paddr) & BCM2835_SPI0_CS_RXD))&&( RXCnt < len ))
         {
            rbuf[RXCnt] = bcm2835_peri_read_nb(fifo);
            RXCnt++;
         }
     }
     /* Wait for DONE to be set */
     while (!(bcm2835_peri_read_nb(paddr) & BCM2835_SPI0_CS_DONE))
     ;
     /* Set TA = 0, and also set the barrier */
     bcm2835_peri_set_bits(paddr, 0, BCM2835_SPI0_CS_TA);
 }
void bcm2835_spi_writenb (char * buf, uint32_t len)
Transfers any number of bytes to the currently selected SPI slave. Asserts the currently selected CS pins (as previously set by bcm2835_spi_chipSelect) during the transfer.
Parameters
[in] buf Buffer of bytes to send.
[in] len Number of bytes in the tbuf buffer, and the number of bytes to send
References bcm2835_peri_read(), bcm2835_peri_read_nb(), bcm2835_peri_set_bits(), bcm2835_peri_write_nb(), bcm2835_spi0, BCM2835_SPI0_CS, BCM2835_SPI0_CS_CLEAR, BCM2835_SPI0_CS_DONE, BCM2835_SPI0_CS_RXD, BCM2835_SPI0_CS_TA, BCM2835_SPI0_CS_TXD, and BCM2835_SPI0_FIFO.
 {
     volatile uint32_t* paddr = bcm2835_spi0 + BCM2835_SPI0_CS/4;
     volatile uint32_t* fifo = bcm2835_spi0 + BCM2835_SPI0_FIFO/4;
     uint32_t i;
     /* This is Polled transfer as per section 10.6.1
     // BUG ALERT: what happens if we get interupted in this section, and someone else
     // accesses a different peripheral?
     // Answer: an ISR is required to issue the required memory barriers.
     */
     /* Clear TX and RX fifos */
     bcm2835_peri_set_bits(paddr, BCM2835_SPI0_CS_CLEAR, BCM2835_SPI0_CS_CLEAR);
     /* Set TA = 1 */
     bcm2835_peri_set_bits(paddr, BCM2835_SPI0_CS_TA, BCM2835_SPI0_CS_TA);
     for (i = 0; i < len; i++)
     {
     /* Maybe wait for TXD */
     while (!(bcm2835_peri_read(paddr) & BCM2835_SPI0_CS_TXD))
         ;
     /* Write to FIFO, no barrier */
     bcm2835_peri_write_nb(fifo, tbuf[i]);
     /* Read from FIFO to prevent stalling */
     while (bcm2835_peri_read(paddr) & BCM2835_SPI0_CS_RXD)
         (void) bcm2835_peri_read_nb(fifo);
     }
     /* Wait for DONE to be set */
     while (!(bcm2835_peri_read_nb(paddr) & BCM2835_SPI0_CS_DONE)) {
     while (bcm2835_peri_read(paddr) & BCM2835_SPI0_CS_RXD)
         (void) bcm2835_peri_read_nb(fifo);
     };
     /* Set TA = 0, and also set the barrier */
     bcm2835_peri_set_bits(paddr, 0, BCM2835_SPI0_CS_TA);
 }