My Project: Low level register access
Low level register access
Functions
uint32_t * bcm2835_regbase (uint8_t regbase)
uint32_t bcm2835_peri_read (volatile uint32_t *paddr)
uint32_t bcm2835_peri_read_nb (volatile uint32_t *paddr)
void bcm2835_peri_write (volatile uint32_t *paddr, uint32_t value)
void bcm2835_peri_write_nb (volatile uint32_t *paddr, uint32_t value)
void bcm2835_peri_set_bits (volatile uint32_t *paddr, uint32_t value, uint32_t mask)
Detailed Description
These functions provide low level register access, and should not generally need to be used
Function Documentation
uint32_t bcm2835_peri_read (volatile uint32_t * paddr)
Reads 32 bit value from a peripheral address WITH a memory barrier before and after each read. This is safe, but slow. The MB before protects this read from any in-flight reads that didn't use a MB. The MB after protects subsequent reads from another peripheral.
Parameters
[in] paddr Physical address to read from. See BCM2835_GPIO_BASE etc.
Returns
the value read from the 32 bit register
See Also
Physical Addresses
Referenced by bcm2835_gpio_eds(), bcm2835_gpio_eds_multi(), bcm2835_gpio_lev(), bcm2835_gpio_pad(), bcm2835_i2c_begin(), bcm2835_i2c_read(), bcm2835_i2c_read_register_rs(), bcm2835_i2c_write(), bcm2835_i2c_write_read_rs(), bcm2835_peri_set_bits(), bcm2835_pwm_set_clock(), bcm2835_pwm_set_mode(), bcm2835_spi_transfer(), bcm2835_spi_transfernb(), bcm2835_spi_writenb(), and bcm2835_st_read().
 {
     uint32_t ret;
     if (debug)
     {
         printf("bcm2835_peri_read  paddr %08X\n", (unsigned) paddr);
     return 0;
     }
     else
     {
        __sync_synchronize();
        ret = *paddr;
        __sync_synchronize();
        return ret;
     }
 }
uint32_t bcm2835_peri_read_nb (volatile uint32_t * paddr)
Reads 32 bit value from a peripheral address WITHOUT the read barriers You should only use this when: o your code has previously called bcm2835_peri_read() for a register within the same peripheral, and no read or write to another peripheral has occurred since. o your code has called bcm2835_memory_barrier() since the last access to ANOTHER peripheral.
Parameters
[in] paddr Physical address to read from. See BCM2835_GPIO_BASE etc.
Returns
the value read from the 32 bit register
See Also
Physical Addresses
Referenced by bcm2835_i2c_read(), bcm2835_i2c_write_read_rs(), bcm2835_spi_transfer(), bcm2835_spi_transfernb(), and bcm2835_spi_writenb().
 {
     if (debug)
     {
     printf("bcm2835_peri_read_nb  paddr %08X\n", (unsigned) paddr);
     return 0;
     }
     else
     {
     return *paddr;
     }
 }
void bcm2835_peri_set_bits (volatile uint32_t * paddr, uint32_t value, uint32_t mask)
Alters a number of bits in a 32 peripheral regsiter. It reads the current valu and then alters the bits defines as 1 in mask, according to the bit value in value. All other bits that are 0 in the mask are unaffected. Use this to alter a subset of the bits in a register. Memory barriers are used. Note that this is not atomic; an interrupt routine can cause unexpected results.
Parameters
[in] paddr Physical address to read from. See BCM2835_GPIO_BASE etc.
[in] value The 32 bit value to write, masked in by mask.
[in] mask Bitmask that defines the bits that will be altered in the register.
See Also
Physical Addresses
References bcm2835_peri_read(), and bcm2835_peri_write().
Referenced by bcm2835_gpio_afen(), bcm2835_gpio_aren(), bcm2835_gpio_clr_afen(), bcm2835_gpio_clr_aren(), bcm2835_gpio_clr_fen(), bcm2835_gpio_clr_hen(), bcm2835_gpio_clr_len(), bcm2835_gpio_clr_ren(), bcm2835_gpio_fen(), bcm2835_gpio_fsel(), bcm2835_gpio_hen(), bcm2835_gpio_len(), bcm2835_gpio_ren(), bcm2835_i2c_read(), bcm2835_i2c_read_register_rs(), bcm2835_i2c_write(), bcm2835_i2c_write_read_rs(), bcm2835_spi_chipSelect(), bcm2835_spi_setChipSelectPolarity(), bcm2835_spi_setDataMode(), bcm2835_spi_transfer(), bcm2835_spi_transfernb(), and bcm2835_spi_writenb().
 {
     uint32_t v = bcm2835_peri_read(paddr);
     v = (v & ~mask) | (value & mask);
     bcm2835_peri_write(paddr, v);
 }
void bcm2835_peri_write (volatile uint32_t * paddr, uint32_t value)
Writes 32 bit value from a peripheral address WITH a memory barrier before and after each write This is safe, but slow. The MB before ensures that any in-flight write to another peripheral completes before this write is issued. The MB after ensures that subsequent reads and writes to another peripheral will see the effect of this write.
This is a tricky optimization; if you aren't sure, use the barrier version.
Parameters
[in] paddr Physical address to read from. See BCM2835_GPIO_BASE etc.
[in] value The 32 bit value to write
See Also
Physical Addresses
Referenced by bcm2835_gpio_clr(), bcm2835_gpio_clr_multi(), bcm2835_gpio_pud(), bcm2835_gpio_pudclk(), bcm2835_gpio_set(), bcm2835_gpio_set_eds(), bcm2835_gpio_set_eds_multi(), bcm2835_gpio_set_multi(), bcm2835_gpio_set_pad(), bcm2835_i2c_read_register_rs(), bcm2835_i2c_setClockDivider(), bcm2835_i2c_setSlaveAddress(), bcm2835_i2c_write(), bcm2835_i2c_write_read_rs(), bcm2835_peri_set_bits(), bcm2835_pwm_set_clock(), bcm2835_spi_begin(), and bcm2835_spi_setClockDivider().
 {
     if (debug)
     {
     printf("bcm2835_peri_write paddr %08X, value %08X\n", (unsigned) paddr, value);
     }
     else
     {
         __sync_synchronize();
         *paddr = value;
         __sync_synchronize();
     }
 }
void bcm2835_peri_write_nb (volatile uint32_t * paddr, uint32_t value)
Writes 32 bit value from a peripheral address without the write barrier You should only use this when: o your code has previously called bcm2835_peri_write() for a register within the same peripheral, and no other peripheral access has occurred since. o your code has called bcm2835_memory_barrier() since the last access to ANOTHER peripheral.
This is a tricky optimization; if you aren't sure, use the barrier version.
Parameters
[in] paddr Physical address to read from. See BCM2835_GPIO_BASE etc.
[in] value The 32 bit value to write
See Also
Physical Addresses
Referenced by bcm2835_i2c_read(), bcm2835_i2c_write(), bcm2835_i2c_write_read_rs(), bcm2835_pwm_set_data(), bcm2835_pwm_set_mode(), bcm2835_pwm_set_range(), bcm2835_spi_begin(), bcm2835_spi_transfer(), bcm2835_spi_transfernb(), and bcm2835_spi_writenb().
 {
     if (debug)
     {
     printf("bcm2835_peri_write_nb paddr %08X, value %08X\n",
                (unsigned) paddr, value);
     }
     else
     {
     *paddr = value;
     }
 }
uint32_t* bcm2835_regbase (uint8_t regbase)
Gets the base of a register
Parameters
[in] regbase You can use one of the common values BCM2835_REGBASE_* in bcm2835RegisterBase
Returns
the register base
See Also
Physical Addresses
References bcm2835_bsc0, bcm2835_clk, bcm2835_gpio, bcm2835_pads, bcm2835_pwm, BCM2835_REGBASE_BSC0, BCM2835_REGBASE_BSC1, BCM2835_REGBASE_CLK, BCM2835_REGBASE_GPIO, BCM2835_REGBASE_PADS, BCM2835_REGBASE_PWM, BCM2835_REGBASE_SPI0, BCM2835_REGBASE_ST, bcm2835_spi0, and bcm2835_st.
 {
     switch (regbase)
     {
     case BCM2835_REGBASE_ST:
         return (uint32_t *)bcm2835_st;
     case BCM2835_REGBASE_GPIO:
         return (uint32_t *)bcm2835_gpio;
     case BCM2835_REGBASE_PWM:
         return (uint32_t *)bcm2835_pwm;
     case BCM2835_REGBASE_CLK:
         return (uint32_t *)bcm2835_clk;
     case BCM2835_REGBASE_PADS:
         return (uint32_t *)bcm2835_pads;
     case BCM2835_REGBASE_SPI0:
         return (uint32_t *)bcm2835_spi0;
     case BCM2835_REGBASE_BSC0:
         return (uint32_t *)bcm2835_bsc0;
     case BCM2835_REGBASE_BSC1:
         return (uint32_t *)bcm2835_st;
     }
     return (uint32_t *)MAP_FAILED;
 }