My Project: GPIO register access
GPIO register access
Functions
void bcm2835_gpio_fsel (uint8_t pin, uint8_t mode)
void bcm2835_gpio_set (uint8_t pin)
void bcm2835_gpio_clr (uint8_t pin)
void bcm2835_gpio_set_multi (uint32_t mask)
void bcm2835_gpio_clr_multi (uint32_t mask)
uint8_t bcm2835_gpio_lev (uint8_t pin)
uint8_t bcm2835_gpio_eds (uint8_t pin)
uint32_t bcm2835_gpio_eds_multi (uint32_t mask)
void bcm2835_gpio_set_eds (uint8_t pin)
void bcm2835_gpio_set_eds_multi (uint32_t mask)
void bcm2835_gpio_ren (uint8_t pin)
void bcm2835_gpio_clr_ren (uint8_t pin)
void bcm2835_gpio_fen (uint8_t pin)
void bcm2835_gpio_clr_fen (uint8_t pin)
void bcm2835_gpio_hen (uint8_t pin)
void bcm2835_gpio_clr_hen (uint8_t pin)
void bcm2835_gpio_len (uint8_t pin)
void bcm2835_gpio_clr_len (uint8_t pin)
void bcm2835_gpio_aren (uint8_t pin)
void bcm2835_gpio_clr_aren (uint8_t pin)
void bcm2835_gpio_afen (uint8_t pin)
void bcm2835_gpio_clr_afen (uint8_t pin)
void bcm2835_gpio_pud (uint8_t pud)
void bcm2835_gpio_pudclk (uint8_t pin, uint8_t on)
uint32_t bcm2835_gpio_pad (uint8_t group)
void bcm2835_gpio_set_pad (uint8_t group, uint32_t control)
void bcm2835_delay (unsigned int millis)
void bcm2835_delayMicroseconds (uint64_t micros)
void bcm2835_gpio_write (uint8_t pin, uint8_t on)
void bcm2835_gpio_write_multi (uint32_t mask, uint8_t on)
void bcm2835_gpio_write_mask (uint32_t value, uint32_t mask)
void bcm2835_gpio_set_pud (uint8_t pin, uint8_t pud)
Detailed Description
These functions allow you to control the GPIO interface. You can set the function of each GPIO pin, read the input state and set the output state.
Function Documentation
void bcm2835_delay (unsigned int millis)
Delays for the specified number of milliseconds. Uses nanosleep(), and therefore does not use CPU until the time is up. However, you are at the mercy of nanosleep(). From the manual for nanosleep(): If the interval specified in req is not an exact multiple of the granularity underlying clock (see time(7)), then the interval will be rounded up to the next multiple. Furthermore, after the sleep completes, there may still be a delay before the CPU becomes free to once again execute the calling thread.
Parameters
[in] millis Delay in milliseconds
Referenced by bcm2835_pwm_set_clock().
 {
     struct timespec sleeper;
     sleeper.tv_sec  = (time_t)(millis / 1000);
     sleeper.tv_nsec = (long)(millis % 1000) * 1000000;
     nanosleep(&sleeper, NULL);
 }
void bcm2835_delayMicroseconds (uint64_t micros)
Delays for the specified number of microseconds. Uses a combination of nanosleep() and a busy wait loop on the BCM2835 system timers, However, you are at the mercy of nanosleep(). From the manual for nanosleep(): If the interval specified in req is not an exact multiple of the granularity underlying clock (see time(7)), then the interval will be rounded up to the next multiple. Furthermore, after the sleep completes, there may still be a delay before the CPU becomes free to once again execute the calling thread. For times less than about 450 microseconds, uses a busy wait on the System Timer. It is reported that a delay of 0 microseconds on RaspberryPi will in fact result in a delay of about 80 microseconds. Your mileage may vary.
Parameters
[in] micros Delay in microseconds
References bcm2835_st_delay(), and bcm2835_st_read().
Referenced by bcm2835_i2c_read_register_rs(), and bcm2835_i2c_write_read_rs().
 {
     struct timespec t1;
     uint64_t        start;
     if (debug)
     {
     /* Cant access sytem timers in debug mode */
     printf("bcm2835_delayMicroseconds %lld\n", micros);
     return;
     }
     /* Calling nanosleep() takes at least 100-200 us, so use it for
     // long waits and use a busy wait on the System Timer for the rest.
     */
     start =  bcm2835_st_read();
     if (micros > 450)
     {
     t1.tv_sec = 0;
     t1.tv_nsec = 1000 * (long)(micros - 200);
     nanosleep(&t1, NULL);
     }
     bcm2835_st_delay(start, micros);
 }
void bcm2835_gpio_afen (uint8_t pin)
Enable Asynchronous Falling Edge Detect Enable for the specified pin. When a falling edge is detected, sets the appropriate pin in Event Detect Status. Asynchronous means the incoming signal is not sampled by the system clock. As such falling edges of very short duration can be detected.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPAFEN0, bcm2835_gpio, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPAFEN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, value, value);
 }
void bcm2835_gpio_aren (uint8_t pin)
Enable Asynchronous Rising Edge Detect Enable for the specified pin. When a rising edge is detected, sets the appropriate pin in Event Detect Status. Asynchronous means the incoming signal is not sampled by the system clock. As such rising edges of very short duration can be detected.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPAREN0, bcm2835_gpio, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPAREN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, value, value);
 }
void bcm2835_gpio_clr (uint8_t pin)
Sets the specified pin output to LOW.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
See Also
bcm2835_gpio_write()
References BCM2835_GPCLR0, bcm2835_gpio, and bcm2835_peri_write().
Referenced by bcm2835_gpio_write().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPCLR0/4 + pin/32;
     uint8_t shift = pin % 32;
     bcm2835_peri_write(paddr, 1 << shift);
 }
void bcm2835_gpio_clr_afen (uint8_t pin)
Disable Asynchronous Falling Edge Detect Enable for the specified pin.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPAFEN0, bcm2835_gpio, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPAFEN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, 0, value);
 }
void bcm2835_gpio_clr_aren (uint8_t pin)
Disable Asynchronous Rising Edge Detect Enable for the specified pin.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPAREN0, bcm2835_gpio, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPAREN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, 0, value);
 }
void bcm2835_gpio_clr_fen (uint8_t pin)
Disable Falling Edge Detect Enable for the specified pin.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPFEN0, bcm2835_gpio, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPFEN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, 0, value);
 }
void bcm2835_gpio_clr_hen (uint8_t pin)
Disable High Detect Enable for the specified pin.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPHEN0, bcm2835_gpio, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPHEN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, 0, value);
 }
void bcm2835_gpio_clr_len (uint8_t pin)
Disable Low Detect Enable for the specified pin.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References bcm2835_gpio, BCM2835_GPLEN0, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPLEN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, 0, value);
 }
void bcm2835_gpio_clr_multi (uint32_t mask)
Sets any of the first 32 GPIO output pins specified in the mask to LOW.
Parameters
[in] mask Mask of pins to affect. Use eg: (1 << RPI_GPIO_P1_03) | (1 << RPI_GPIO_P1_05)
See Also
bcm2835_gpio_write_multi()
References BCM2835_GPCLR0, bcm2835_gpio, and bcm2835_peri_write().
Referenced by bcm2835_gpio_write_mask(), and bcm2835_gpio_write_multi().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPCLR0/4;
     bcm2835_peri_write(paddr, mask);
 }
void bcm2835_gpio_clr_ren (uint8_t pin)
Disable Rising Edge Detect Enable for the specified pin.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References bcm2835_gpio, BCM2835_GPREN0, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPREN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, 0, value);
 }
uint8_t bcm2835_gpio_eds (uint8_t pin)
Event Detect Status. Tests whether the specified pin has detected a level or edge as requested by bcm2835_gpio_ren(), bcm2835_gpio_fen(), bcm2835_gpio_hen(), bcm2835_gpio_len(), bcm2835_gpio_aren(), bcm2835_gpio_afen(). Clear the flag for a given pin by calling bcm2835_gpio_set_eds(pin);
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
Returns
HIGH if the event detect status for the given pin is true.
References BCM2835_GPEDS0, bcm2835_gpio, bcm2835_peri_read(), HIGH, and LOW.
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPEDS0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = bcm2835_peri_read(paddr);
     return (value & (1 << shift)) ? HIGH : LOW;
 }
uint32_t bcm2835_gpio_eds_multi (uint32_t mask)
Same as bcm2835_gpio_eds() but checks if any of the pins specified in the mask have detected a level or edge.
Parameters
[in] mask Mask of pins to check. Use eg: (1 << RPI_GPIO_P1_03) | (1 << RPI_GPIO_P1_05)
Returns
Mask of pins HIGH if the event detect status for the given pin is true.
References BCM2835_GPEDS0, bcm2835_gpio, and bcm2835_peri_read().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPEDS0/4;
     uint32_t value = bcm2835_peri_read(paddr);
     return (value & mask);
 }
void bcm2835_gpio_fen (uint8_t pin)
Enable Falling Edge Detect Enable for the specified pin. When a falling edge is detected, sets the appropriate pin in Event Detect Status. The GPRENn registers use synchronous edge detection. This means the input signal is sampled using the system clock and then it is looking for a ?100? pattern on the sampled signal. This has the effect of suppressing glitches.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPFEN0, bcm2835_gpio, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPFEN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, value, value);
 }
void bcm2835_gpio_fsel (uint8_t pin, uint8_t mode)
Sets the Function Select register for the given pin, which configures the pin as Input, Output or one of the 6 alternate functions.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
[in] mode Mode to set the pin to, one of BCM2835_GPIO_FSEL_* from bcm2835FunctionSelect
References BCM2835_GPFSEL0, bcm2835_gpio, BCM2835_GPIO_FSEL_MASK, and bcm2835_peri_set_bits().
Referenced by bcm2835_i2c_begin(), bcm2835_i2c_end(), bcm2835_spi_begin(), and bcm2835_spi_end().
 {
     /* Function selects are 10 pins per 32 bit word, 3 bits per pin */
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPFSEL0/4 + (pin/10);
     uint8_t   shift = (pin % 10) * 3;
     uint32_t  mask = BCM2835_GPIO_FSEL_MASK << shift;
     uint32_t  value = mode << shift;
     bcm2835_peri_set_bits(paddr, value, mask);
 }
void bcm2835_gpio_hen (uint8_t pin)
Enable High Detect Enable for the specified pin. When a HIGH level is detected on the pin, sets the appropriate pin in Event Detect Status.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPHEN0, bcm2835_gpio, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPHEN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, value, value);
 }
void bcm2835_gpio_len (uint8_t pin)
Enable Low Detect Enable for the specified pin. When a LOW level is detected on the pin, sets the appropriate pin in Event Detect Status.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References bcm2835_gpio, BCM2835_GPLEN0, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPLEN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, value, value);
 }
uint8_t bcm2835_gpio_lev (uint8_t pin)
Reads the current level on the specified pin and returns either HIGH or LOW. Works whether or not the pin is an input or an output.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
Returns
the current level either HIGH or LOW
References bcm2835_gpio, BCM2835_GPLEV0, bcm2835_peri_read(), HIGH, and LOW.
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPLEV0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = bcm2835_peri_read(paddr);
     return (value & (1 << shift)) ? HIGH : LOW;
 }
uint32_t bcm2835_gpio_pad (uint8_t group)
Reads and returns the Pad Control for the given GPIO group.
Parameters
[in] group The GPIO pad group number, one of BCM2835_PAD_GROUP_GPIO_*
Returns
Mask of bits from BCM2835_PAD_* from bcm2835PadGroup
References bcm2835_pads, BCM2835_PADS_GPIO_0_27, and bcm2835_peri_read().
 {
     volatile uint32_t* paddr = bcm2835_pads + BCM2835_PADS_GPIO_0_27/4 + group;
     return bcm2835_peri_read(paddr);
 }
void bcm2835_gpio_pud (uint8_t pud)
Sets the Pull-up/down register for the given pin. This is used with bcm2835_gpio_pudclk() to set the Pull-up/down resistor for the given pin. However, it is usually more convenient to use bcm2835_gpio_set_pud().
Parameters
[in] pud The desired Pull-up/down mode. One of BCM2835_GPIO_PUD_* from bcm2835PUDControl
See Also
bcm2835_gpio_set_pud()
References bcm2835_gpio, BCM2835_GPPUD, and bcm2835_peri_write().
Referenced by bcm2835_gpio_set_pud().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPPUD/4;
     bcm2835_peri_write(paddr, pud);
 }
void bcm2835_gpio_pudclk (uint8_t pin, uint8_t on)
Clocks the Pull-up/down value set earlier by bcm2835_gpio_pud() into the pin.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
[in] on HIGH to clock the value from bcm2835_gpio_pud() into the pin. LOW to remove the clock.
See Also
bcm2835_gpio_set_pud()
References bcm2835_gpio, BCM2835_GPPUDCLK0, and bcm2835_peri_write().
Referenced by bcm2835_gpio_set_pud().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPPUDCLK0/4 + pin/32;
     uint8_t shift = pin % 32;
     bcm2835_peri_write(paddr, (on ? 1 : 0) << shift);
 }
void bcm2835_gpio_ren (uint8_t pin)
Enable Rising Edge Detect Enable for the specified pin. When a rising edge is detected, sets the appropriate pin in Event Detect Status. The GPRENn registers use synchronous edge detection. This means the input signal is sampled using the system clock and then it is looking for a ?011? pattern on the sampled signal. This has the effect of suppressing glitches.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References bcm2835_gpio, BCM2835_GPREN0, and bcm2835_peri_set_bits().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPREN0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_set_bits(paddr, value, value);
 }
void bcm2835_gpio_set (uint8_t pin)
Sets the specified pin output to HIGH.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
See Also
bcm2835_gpio_write()
References bcm2835_gpio, BCM2835_GPSET0, and bcm2835_peri_write().
Referenced by bcm2835_gpio_write().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPSET0/4 + pin/32;
     uint8_t shift = pin % 32;
     bcm2835_peri_write(paddr, 1 << shift);
 }
void bcm2835_gpio_set_eds (uint8_t pin)
Sets the Event Detect Status register for a given pin to 1, which has the effect of clearing the flag. Use this afer seeing an Event Detect Status on the pin.
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
References BCM2835_GPEDS0, bcm2835_gpio, and bcm2835_peri_write().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPEDS0/4 + pin/32;
     uint8_t shift = pin % 32;
     uint32_t value = 1 << shift;
     bcm2835_peri_write(paddr, value);
 }
void bcm2835_gpio_set_eds_multi (uint32_t mask)
Same as bcm2835_gpio_set_eds() but clears the flag for any pin which is set in the mask.
Parameters
[in] mask Mask of pins to clear. Use eg: (1 << RPI_GPIO_P1_03) | (1 << RPI_GPIO_P1_05)
References BCM2835_GPEDS0, bcm2835_gpio, and bcm2835_peri_write().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPEDS0/4;
     bcm2835_peri_write(paddr, mask);
 }
void bcm2835_gpio_set_multi (uint32_t mask)
Sets any of the first 32 GPIO output pins specified in the mask to HIGH.
Parameters
[in] mask Mask of pins to affect. Use eg: (1 << RPI_GPIO_P1_03) | (1 << RPI_GPIO_P1_05)
See Also
bcm2835_gpio_write_multi()
References bcm2835_gpio, BCM2835_GPSET0, and bcm2835_peri_write().
Referenced by bcm2835_gpio_write_mask(), and bcm2835_gpio_write_multi().
 {
     volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPSET0/4;
     bcm2835_peri_write(paddr, mask);
 }
void bcm2835_gpio_set_pad (uint8_t group, uint32_t control)
Sets the Pad Control for the given GPIO group.
Parameters
[in] group The GPIO pad group number, one of BCM2835_PAD_GROUP_GPIO_*
[in] control Mask of bits from BCM2835_PAD_* from bcm2835PadGroup. Note that it is not necessary to include BCM2835_PAD_PASSWRD in the mask as this is automatically included.
References BCM2835_PAD_PASSWRD, bcm2835_pads, BCM2835_PADS_GPIO_0_27, and bcm2835_peri_write().
 {
     volatile uint32_t* paddr = bcm2835_pads + BCM2835_PADS_GPIO_0_27/4 + group;
     bcm2835_peri_write(paddr, control | BCM2835_PAD_PASSWRD);
 }
void bcm2835_gpio_set_pud (uint8_t pin, uint8_t pud)
Sets the Pull-up/down mode for the specified pin. This is more convenient than clocking the mode in with bcm2835_gpio_pud() and bcm2835_gpio_pudclk().
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
[in] pud The desired Pull-up/down mode. One of BCM2835_GPIO_PUD_* from bcm2835PUDControl
References bcm2835_gpio_pud(), BCM2835_GPIO_PUD_OFF, and bcm2835_gpio_pudclk().
 {
     bcm2835_gpio_pud(pud);
     delayMicroseconds(10);
     bcm2835_gpio_pudclk(pin, 1);
     delayMicroseconds(10);
     bcm2835_gpio_pud(BCM2835_GPIO_PUD_OFF);
     bcm2835_gpio_pudclk(pin, 0);
 }
void bcm2835_gpio_write (uint8_t pin, uint8_t on)
Sets the output state of the specified pin
Parameters
[in] pin GPIO number, or one of RPI_GPIO_P1_* from RPiGPIOPin.
[in] on HIGH sets the output to HIGH and LOW to LOW.
References bcm2835_gpio_clr(), and bcm2835_gpio_set().
 {
     if (on)
     bcm2835_gpio_set(pin);
     else
     bcm2835_gpio_clr(pin);
 }
void bcm2835_gpio_write_mask (uint32_t value, uint32_t mask)
Sets the first 32 GPIO output pins specified in the mask to the value given by value
Parameters
[in] value values required for each bit masked in by mask, eg: (1 << RPI_GPIO_P1_03) | (1 << RPI_GPIO_P1_05)
[in] mask Mask of pins to affect. Use eg: (1 << RPI_GPIO_P1_03) | (1 << RPI_GPIO_P1_05)
References bcm2835_gpio_clr_multi(), and bcm2835_gpio_set_multi().
 {
     bcm2835_gpio_set_multi(value & mask);
     bcm2835_gpio_clr_multi((~value) & mask);
 }
void bcm2835_gpio_write_multi (uint32_t mask, uint8_t on)
Sets any of the first 32 GPIO output pins specified in the mask to the state given by on
Parameters
[in] mask Mask of pins to affect. Use eg: (1 << RPI_GPIO_P1_03) | (1 << RPI_GPIO_P1_05)
[in] on HIGH sets the output to HIGH and LOW to LOW.
References bcm2835_gpio_clr_multi(), and bcm2835_gpio_set_multi().
 {
     if (on)
     bcm2835_gpio_set_multi(mask);
     else
     bcm2835_gpio_clr_multi(mask);
 }