My Project: Pulse Width Modulation
Pulse Width Modulation
Functions
void bcm2835_pwm_set_clock (uint32_t divisor)
void bcm2835_pwm_set_mode (uint8_t channel, uint8_t markspace, uint8_t enabled)
void bcm2835_pwm_set_range (uint8_t channel, uint32_t range)
void bcm2835_pwm_set_data (uint8_t channel, uint32_t data)
Detailed Description
Allows control of 2 independent PWM channels. A limited subset of GPIO pins can be connected to one of these 2 channels, allowing PWM control of GPIO pins. You have to set the desired pin into a particular Alt Fun to PWM output. See the PWM documentation on the Main Page.
Function Documentation
void bcm2835_pwm_set_clock (uint32_t divisor)
Sets the PWM clock divisor, to control the basic PWM pulse widths.
Parameters
[in] divisor Divides the basic 19.2MHz PWM clock. You can use one of the common values BCM2835_PWM_CLOCK_DIVIDER_* in bcm2835PWMClockDivider
References bcm2835_clk, bcm2835_delay(), bcm2835_peri_read(), and bcm2835_peri_write().
 {
     /* From Gerts code */
     divisor &= 0xfff;
     /* Stop PWM clock */
     bcm2835_peri_write(bcm2835_clk + BCM2835_PWMCLK_CNTL, BCM2835_PWM_PASSWRD | 0x01);
     bcm2835_delay(110); /* Prevents clock going slow */
     /* Wait for the clock to be not busy */
     while ((bcm2835_peri_read(bcm2835_clk + BCM2835_PWMCLK_CNTL) & 0x80) != 0)
     bcm2835_delay(1);
     /* set the clock divider and enable PWM clock */
     bcm2835_peri_write(bcm2835_clk + BCM2835_PWMCLK_DIV, BCM2835_PWM_PASSWRD | (divisor << 12));
     bcm2835_peri_write(bcm2835_clk + BCM2835_PWMCLK_CNTL, BCM2835_PWM_PASSWRD | 0x11); /* Source=osc and enable */
 }
void bcm2835_pwm_set_data (uint8_t channel, uint32_t data)
Sets the PWM pulse ratio to emit to DATA/RANGE, where RANGE is set by bcm2835_pwm_set_range().
Parameters
[in] channel The PWM channel. 0 or 1.
[in] data Controls the PWM output ratio as a fraction of the range. Can vary from 0 to RANGE.
References bcm2835_peri_write_nb(), and bcm2835_pwm.
 {
   if (channel == 0)
       bcm2835_peri_write_nb(bcm2835_pwm + BCM2835_PWM0_DATA, data);
   else if (channel == 1)
       bcm2835_peri_write_nb(bcm2835_pwm + BCM2835_PWM1_DATA, data);
 }
void bcm2835_pwm_set_mode (uint8_t channel, uint8_t markspace, uint8_t enabled)
Sets the mode of the given PWM channel, allowing you to control the PWM mode and enable/disable that channel
Parameters
[in] channel The PWM channel. 0 or 1.
[in] markspace Set true if you want Mark-Space mode. 0 for Balanced mode.
[in] enabled Set true to enable this channel and produce PWM pulses.
References bcm2835_peri_read(), bcm2835_peri_write_nb(), and bcm2835_pwm.
 {
   uint32_t control = bcm2835_peri_read(bcm2835_pwm + BCM2835_PWM_CONTROL);
   if (channel == 0)
     {
       if (markspace)
     control |= BCM2835_PWM0_MS_MODE;
       else
     control &= ~BCM2835_PWM0_MS_MODE;
       if (enabled)
     control |= BCM2835_PWM0_ENABLE;
       else
     control &= ~BCM2835_PWM0_ENABLE;
     }
   else if (channel == 1)
     {
       if (markspace)
     control |= BCM2835_PWM1_MS_MODE;
       else
     control &= ~BCM2835_PWM1_MS_MODE;
       if (enabled)
     control |= BCM2835_PWM1_ENABLE;
       else
     control &= ~BCM2835_PWM1_ENABLE;
     }
   /* If you use the barrier here, wierd things happen, and the commands dont work */
   bcm2835_peri_write_nb(bcm2835_pwm + BCM2835_PWM_CONTROL, control);
   /*  bcm2835_peri_write_nb(bcm2835_pwm + BCM2835_PWM_CONTROL, BCM2835_PWM0_ENABLE | BCM2835_PWM1_ENABLE | BCM2835_PWM0_MS_MODE | BCM2835_PWM1_MS_MODE); */
 }
void bcm2835_pwm_set_range (uint8_t channel, uint32_t range)
Sets the maximum range of the PWM output. The data value can vary between 0 and this range to control PWM output
Parameters
[in] channel The PWM channel. 0 or 1.
[in] range The maximum value permitted for DATA.
References bcm2835_peri_write_nb(), and bcm2835_pwm.
 {
   if (channel == 0)
       bcm2835_peri_write_nb(bcm2835_pwm + BCM2835_PWM0_RANGE, range);
   else if (channel == 1)
       bcm2835_peri_write_nb(bcm2835_pwm + BCM2835_PWM1_RANGE, range);
 }