My Project: System Timer access
System Timer access
Functions
uint64_t bcm2835_st_read (void)
void bcm2835_st_delay (uint64_t offset_micros, uint64_t micros)
Detailed Description
Allows access to and delays using the System Timer Counter.
Function Documentation
void bcm2835_st_delay (uint64_t offset_micros, uint64_t micros)
Delays for the specified number of microseconds with offset.
Parameters
[in] offset_micros Offset in microseconds
[in] micros Delay in microseconds
References bcm2835_st_read().
Referenced by bcm2835_delayMicroseconds().
 {
     uint64_t compare = offset_micros + micros;
     while(bcm2835_st_read() < compare)
     ;
 }
uint64_t bcm2835_st_read (void)
Read the System Timer Counter register.
Returns
the value read from the System Timer Counter Lower 32 bits register
References bcm2835_peri_read(), bcm2835_st, BCM2835_ST_CHI, and BCM2835_ST_CLO.
Referenced by bcm2835_delayMicroseconds(), and bcm2835_st_delay().
 {
     volatile uint32_t* paddr;
     uint32_t hi, lo;
     uint64_t st;
     paddr = bcm2835_st + BCM2835_ST_CHI/4;
     hi = bcm2835_peri_read(paddr);
     paddr = bcm2835_st + BCM2835_ST_CLO/4;
     lo = bcm2835_peri_read(paddr);
     paddr = bcm2835_st + BCM2835_ST_CHI/4;
     st = bcm2835_peri_read(paddr);
     /* Test for overflow */
     if (st == hi)
     {
         st <<= 32;
         st += lo;
     }
     else
     {
         st <<= 32;
         paddr = bcm2835_st + BCM2835_ST_CLO/4;
         st += bcm2835_peri_read(paddr);
     }
     return st;
 }